import type { CSSProperties } from 'react';

export const S: Record<string, CSSProperties> = {
  card: {
    display: 'flex',
    flexDirection: 'column',
    background: '#ffffff',
    border: '1px solid #e0e0e0',
    borderRadius: '12px',
    boxShadow: '0 3px 4px rgba(0,0,0,0.12)',
    overflow: 'hidden',
  },
  header: {
    padding: '0.75rem 1rem',
    borderBottom: '1px solid #e9e9e7',
  },
  h3: {
    margin: '0 0 0.2rem 0',
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#37352f',
  },
  desc: {
    margin: 0,
    fontSize: '0.7rem',
    color: '#6b6b6b',
  },
  content: {
    padding: '0.75rem 1rem',
    overflowY: 'auto',
    maxHeight: '320px',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
  },
  actions: {
    display: 'flex',
    gap: '0.5rem',
    padding: '0.75rem 1rem',
    borderTop: '1px solid #e9e9e7',
  },
  cancelBtn: {
    flex: 1,
    padding: '0.5rem',
    background: '#f7f6f3',
    color: '#37352f',
    border: '1px solid #e0e0e0',
    borderRadius: '3px',
    fontSize: '0.75rem',
    fontWeight: 500,
    cursor: 'pointer',
  },
  submitBtn: {
    flex: 2,
    padding: '0.5rem',
    background: '#2383e2',
    color: 'white',
    border: 'none',
    borderRadius: '3px',
    fontSize: '0.75rem',
    fontWeight: 500,
    cursor: 'pointer',
  },
  label: {
    display: 'block',
    marginBottom: '0.25rem',
    fontSize: '0.7rem',
    fontWeight: 500,
    color: '#37352f',
  },
  input: {
    width: '100%',
    padding: '0.4rem',
    border: '1px solid #e9e9e7',
    borderRadius: '3px',
    fontSize: '0.7rem',
    fontFamily: 'inherit',
    color: '#37352f',
    boxSizing: 'border-box',
    background: 'white',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0.5rem',
  },
};
